import React from "react";
import {
  Award,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  ChartNoAxesColumnIncreasing,
  GraduationCap,
  HardHat,
  PieChart,
  TrendingUp,
  Users,
  Check,
  CheckCircle2,
  WalletCards,
  BrainCircuit,
  Megaphone,
  Globe,
  Globe2,
  Lightbulb,
  BookOpenCheck,
  Landmark,
  Target,
  UsersRound,
  Calculator,
  BadgeDollarSign,
  Phone,
  MapPin,
  LaptopMinimal,
  Quote,
  ChevronDown,
  ArrowUpRight,
  ArrowDownRight,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  Award,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  ChartNoAxesColumnIncreasing,
  GraduationCap,
  HardHat,
  PieChart,
  TrendingUp,
  Users,
  Check,
  CheckCircle2,
  WalletCards,
  BrainCircuit,
  Megaphone,
  Globe,
  Globe2,
  Lightbulb,
  BookOpenCheck,
  Landmark,
  Target,
  UsersRound,
  Calculator,
  BadgeDollarSign,
  Phone,
  MapPin,
  LaptopMinimal,
  Quote,
  ChevronDown,
  ArrowUpRight,
  ArrowDownRight,
};

export function getProgramIcon(name?: string, fallback: LucideIcon = GraduationCap): LucideIcon {
  if (!name) return fallback;
  return ICON_MAP[name] || fallback;
}
